from __future__ import annotations

from typing import Any


BASE_THEME = {
    "bg": "#f3ece3",
    "bg_alt": "#e6d8c8",
    "panel": "rgba(255, 251, 245, 0.86)",
    "panel_strong": "rgba(255, 248, 242, 0.96)",
    "ink": "#1d2430",
    "muted": "#5f6c7c",
    "line": "rgba(29, 36, 48, 0.11)",
    "accent": "#0f766e",
    "accent_2": "#d97706",
    "accent_3": "#1d4ed8",
    "accent_4": "#b91c1c",
    "shadow": "0 24px 60px rgba(17, 24, 39, 0.16)",
    "hero_font": '"IBM Plex Sans", "Trebuchet MS", sans-serif',
    "body_font": '"IBM Plex Sans", "Trebuchet MS", sans-serif',
    "mono_font": '"IBM Plex Mono", monospace',
    "radius_shell": "28px",
    "radius_card": "22px",
    "background_css": "linear-gradient(160deg, #f8f2e8 0%, #f1e6d6 52%, #eadbc9 100%)",
    "overlay_css": "radial-gradient(circle at top left, rgba(15, 118, 110, 0.12), transparent 28%), radial-gradient(circle at right, rgba(217, 119, 6, 0.08), transparent 24%)",
    "overlay_opacity": "1",
    "eyebrow": "GitHub activity report",
    "hero_title": "Your coding weather report, rendered with dramatic flair.",
    "hero_copy": "Commits, pull requests, issues, and language footprints are organized into a static report snapshot that can travel cleanly.",
    "profile_kicker": "Profile",
    "side_kicker": "Coverage",
    "side_title": "A readable snapshot of your coding season",
    "side_copy": "The report folds GitHub activity into a single page with charts, repo highlights, and some fun observations.",
    "stats_kicker": "Key stats",
    "stats_title": "Signal at a glance",
    "charts_kicker": "Timeline",
    "charts_kicker_2": "Code churn",
    "calendar_kicker": "Calendar",
    "language_kicker": "Languages",
    "heatmap_kicker": "Heatmap",
    "language_breakdown_kicker": "Breakdown",
    "language_breakdown_title": "Language mix",
    "highlights_kicker": "Highlights",
    "highlights_title": "Fun facts and notable spikes",
    "repo_kicker": "Repositories",
    "repo_title": "Where the work happened",
    "notes_kicker": "Notes",
    "notes_title": "Warnings and caveats",
    "extra_css": "",
}


def _theme(**overrides: Any) -> dict[str, Any]:
    theme = dict(BASE_THEME)
    theme.update(overrides)
    return theme


REPORT_THEMES: dict[str, dict[str, Any]] = {
    "default": _theme(),
    "ledger": _theme(
        background_css="linear-gradient(180deg, #fbf6ef 0%, #f2e8d8 60%, #eadbc2 100%)",
        overlay_css="linear-gradient(rgba(31, 41, 55, 0.045) 1px, transparent 1px), linear-gradient(90deg, rgba(31, 41, 55, 0.03) 1px, transparent 1px)",
        overlay_opacity="0.7",
        panel="rgba(255, 252, 247, 0.9)",
        panel_strong="rgba(255, 253, 250, 0.98)",
        ink="#241d1a",
        muted="#6b625c",
        line="rgba(36, 29, 26, 0.12)",
        accent="#7b2d26",
        accent_2="#b08968",
        accent_3="#3b4d61",
        accent_4="#8f5f2d",
        hero_font='Georgia, "Times New Roman", serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="The Maintainer's Ledger",
        hero_title="A quarter-end statement for your GitHub output.",
        hero_copy="Less dashboard, more polished ledger: totals, cadence, and repo performance laid out like an annual report.",
        stats_title="Performance statement",
        repo_title="Portfolio holdings",
        highlights_title="Notable movements",
        extra_css=".template-ledger .panel,.template-ledger .hero{border-radius:14px}.template-ledger .chip,.template-ledger .eyebrow{border-radius:4px}.template-ledger h1,.template-ledger h2,.template-ledger h3{letter-spacing:-0.02em}",
    ),
    "transit": _theme(
        background_css="linear-gradient(180deg, #fcfbf6 0%, #f4f0e6 100%)",
        overlay_css="linear-gradient(rgba(52, 52, 52, 0.08) 2px, transparent 2px), linear-gradient(90deg, rgba(52, 52, 52, 0.08) 2px, transparent 2px)",
        overlay_opacity="0.22",
        panel="rgba(255,255,255,0.88)",
        panel_strong="rgba(255,255,255,0.96)",
        ink="#23262b",
        muted="#68707b",
        line="rgba(35,38,43,0.1)",
        accent="#006da8",
        accent_2="#ed8b00",
        accent_3="#00a56a",
        accent_4="#d64545",
        hero_font='"Arial Narrow", "IBM Plex Sans", sans-serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Merge Line Transit Map",
        hero_title="Follow the lines your work took through the network.",
        hero_copy="This version treats your activity like a transit system: routes, stations, and transfers between repos and rhythms.",
        repo_title="Transit lines",
        highlights_title="Stations worth stopping at",
        extra_css=".template-transit .hero,.template-transit .panel{border-radius:18px}.template-transit .chip,.template-transit .eyebrow{font-weight:700}.template-transit .accent-1,.template-transit .accent-2,.template-transit .accent-3,.template-transit .accent-4{border-top-width:6px}",
    ),
    "archive": _theme(
        background_css="linear-gradient(180deg, #f4efe8 0%, #e9dfd3 100%)",
        overlay_css="radial-gradient(circle at top left, rgba(87, 74, 60, 0.08), transparent 25%), radial-gradient(circle at bottom right, rgba(42, 65, 74, 0.08), transparent 22%)",
        panel="rgba(249, 243, 236, 0.88)",
        panel_strong="rgba(252, 248, 243, 0.98)",
        ink="#312822",
        muted="#786d66",
        line="rgba(49,40,34,0.12)",
        accent="#7f5539",
        accent_2="#5c7c72",
        accent_3="#b08968",
        accent_4="#5a6778",
        hero_font='"Palatino Linotype", Georgia, serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Archive Exhibit",
        hero_title="A curated exhibit of your recent GitHub artifacts.",
        hero_copy="Repos become exhibit pieces, charts become labels, and the whole thing reads like a small museum wall for your coding period.",
        side_title="Artifact framing for technical work",
        repo_title="Featured artifacts",
        highlights_title="Curator notes",
        extra_css=".template-archive .hero,.template-archive .panel{box-shadow:0 18px 40px rgba(74,54,40,0.14)}.template-archive .chip,.template-archive .eyebrow{background:rgba(255,255,255,0.55)}",
    ),
    "scrapbook": _theme(
        background_css="linear-gradient(180deg, #fff7ea 0%, #ffe9dd 100%)",
        overlay_css="radial-gradient(circle at top left, rgba(255, 140, 102, 0.16), transparent 24%), radial-gradient(circle at right, rgba(31, 176, 255, 0.14), transparent 22%)",
        panel="rgba(255, 250, 245, 0.86)",
        panel_strong="rgba(255, 252, 248, 0.98)",
        ink="#2b1c18",
        muted="#7a655f",
        line="rgba(43,28,24,0.1)",
        accent="#ff6b57",
        accent_2="#ffbd2f",
        accent_3="#1fb0ff",
        accent_4="#37b56e",
        hero_font='"Trebuchet MS", "Arial Narrow", sans-serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Indie Dev Scrapbook",
        hero_title="A loud little collage of what you shipped and nudged forward.",
        hero_copy="Messier on purpose, brighter on purpose, and much more like a launch diary than a KPI console.",
        highlights_title="Pinned moments",
        repo_title="Stickered repositories",
        extra_css=".template-scrapbook .hero,.template-scrapbook .panel{transform:rotate(-0.2deg)}.template-scrapbook .repo-card:nth-child(even),.template-scrapbook .fact:nth-child(odd){transform:rotate(0.5deg)}.template-scrapbook .chip,.template-scrapbook .eyebrow{box-shadow:3px 3px 0 rgba(0,0,0,0.08)}",
    ),
    "orbital": _theme(
        background_css="radial-gradient(circle at top left, rgba(32, 148, 255, 0.16), transparent 26%), linear-gradient(180deg, #050913 0%, #0a1020 56%, #0d1630 100%)",
        overlay_css="linear-gradient(rgba(90, 216, 255, 0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(90, 216, 255, 0.08) 1px, transparent 1px)",
        overlay_opacity="0.35",
        panel="rgba(6, 11, 22, 0.84)",
        panel_strong="rgba(8, 14, 28, 0.96)",
        ink="#e7f2ff",
        muted="#95a8c5",
        line="rgba(90,216,255,0.14)",
        accent="#5ad8ff",
        accent_2="#9ff5a4",
        accent_3="#f2b15d",
        accent_4="#ff8573",
        hero_font='"IBM Plex Sans", sans-serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Orbital Telemetry Brief",
        hero_title="Mission telemetry for a very online coding vessel.",
        hero_copy="An operational debrief version of your GitHub activity, tuned like a mission packet rather than a product dashboard.",
        side_title="Flight path summary",
        repo_title="Systems touched",
        highlights_title="Telemetry anomalies",
        extra_css=".template-orbital .panel,.template-orbital .hero{backdrop-filter:blur(24px)}.template-orbital .chip,.template-orbital .eyebrow{text-shadow:0 0 16px rgba(90,216,255,0.18)}",
    ),
    "fieldnotes": _theme(
        background_css="linear-gradient(180deg, #f7f1e5 0%, #efe4cf 100%)",
        overlay_css="linear-gradient(rgba(93, 83, 67, 0.05) 1px, transparent 1px)",
        overlay_opacity="0.6",
        panel="rgba(252, 247, 239, 0.88)",
        panel_strong="rgba(255, 251, 245, 0.98)",
        ink="#2f2821",
        muted="#706760",
        line="rgba(47,40,33,0.1)",
        accent="#466a62",
        accent_2="#b25c42",
        accent_3="#7d8c4c",
        accent_4="#9b7c3e",
        hero_font='"Georgia", serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Field Notes",
        hero_title="An expedition log through your recent coding terrain.",
        hero_copy="Notebook logic, margin-note energy, and a little bit of naturalist observation layered on top of the raw GitHub facts.",
        side_title="Collected observations",
        highlights_title="Notebook callouts",
        repo_title="Observed repositories",
        extra_css=".template-fieldnotes .hero,.template-fieldnotes .panel{border-radius:10px}.template-fieldnotes .language-item,.template-fieldnotes .warning,.template-fieldnotes .fact{background:rgba(255,255,255,0.55)}",
    ),
    "signalroom": _theme(
        background_css="linear-gradient(180deg, #060c10 0%, #0b1218 100%)",
        overlay_css="repeating-linear-gradient(180deg, rgba(159,245,164,0.06) 0 2px, transparent 2px 5px)",
        overlay_opacity="0.24",
        panel="rgba(8, 13, 18, 0.84)",
        panel_strong="rgba(10, 16, 22, 0.96)",
        ink="#dcffeb",
        muted="#8ab29b",
        line="rgba(159,245,164,0.14)",
        accent="#9ff5a4",
        accent_2="#f2b15d",
        accent_3="#5ad8ff",
        accent_4="#ff8573",
        hero_font='"Arial Narrow", "IBM Plex Sans", sans-serif',
        body_font='"IBM Plex Sans", sans-serif',
        mono_font='"IBM Plex Mono", monospace',
        eyebrow="Signal Room",
        hero_title="Your development channels, routed through the signal board.",
        hero_copy="A darker broadcast-room interpretation of the same GitHub snapshot: channels, feeds, and pulsing telemetry cues.",
        side_title="Channel summary",
        highlights_title="Signal spikes",
        repo_title="Active feeds",
        extra_css=".template-signalroom .chart-card canvas{filter:saturate(0.85) brightness(0.92)}.template-signalroom .chip,.template-signalroom .eyebrow{background:rgba(159,245,164,0.06)}",
    ),
    "gallery": _theme(
        background_css="linear-gradient(180deg, #f5f0ea 0%, #e9dfd4 100%)",
        overlay_css="radial-gradient(circle at top left, rgba(32, 80, 132, 0.12), transparent 24%), radial-gradient(circle at bottom right, rgba(181, 127, 60, 0.12), transparent 20%)",
        panel="rgba(250, 247, 242, 0.88)",
        panel_strong="rgba(255, 252, 247, 0.98)",
        ink="#2c2632",
        muted="#746d7a",
        line="rgba(44,38,50,0.1)",
        accent="#315ca8",
        accent_2="#b57f3c",
        accent_3="#7f3c8d",
        accent_4="#cc5f2f",
        hero_font='"Georgia", serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Gallery Wall",
        hero_title="A salon-style hanging of your GitHub tendencies.",
        hero_copy="Designed like a poster exhibition: asymmetry, oversized labels, and a more art-directed rhythm for the same analytics.",
        side_title="Curated frame notes",
        highlights_title="Wall text",
        repo_title="Framed projects",
        extra_css=".template-gallery .facts-grid,.template-gallery .repo-grid{grid-template-columns:1.2fr .8fr}.template-gallery .fact:nth-child(3n){transform:translateY(14px)}",
    ),
    "tapearchive": _theme(
        background_css="linear-gradient(180deg, #f6f2ea 0%, #ece4d7 100%)",
        overlay_css="linear-gradient(90deg, rgba(0,0,0,0.04) 0 6%, transparent 6% 100%)",
        overlay_opacity="0.22",
        panel="rgba(252, 249, 244, 0.88)",
        panel_strong="rgba(255, 252, 248, 0.98)",
        ink="#221f22",
        muted="#6d676e",
        line="rgba(34,31,34,0.1)",
        accent="#111111",
        accent_2="#ffb100",
        accent_3="#00a6a6",
        accent_4="#ff6b57",
        hero_font='"Arial Narrow", "IBM Plex Sans", sans-serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Tape Archive",
        hero_title="Boxed, labeled, and filed: your work in archival strips.",
        hero_copy="A tactile index-card and cassette-case take on coding activity, leaning modular and nostalgic without becoming retro terminal cosplay.",
        side_title="Archive metadata",
        highlights_title="Labeled moments",
        repo_title="Catalog entries",
        extra_css=".template-tapearchive .chip,.template-tapearchive .eyebrow{border-radius:4px}.template-tapearchive .repo-card,.template-tapearchive .fact{box-shadow:4px 4px 0 rgba(0,0,0,0.06)}",
    ),

    "cyberpunk": _theme(
        background_css="#0a0a0a",
        overlay_css="repeating-linear-gradient(transparent, transparent 2px, rgba(0,0,0,0.2) 2px, rgba(0,0,0,0.2) 4px)",
        overlay_opacity="1",
        panel="rgba(20, 20, 20, 0.8)",
        panel_strong="rgba(30, 30, 30, 0.9)",
        ink="#00ffff",
        muted="#ff00ff",
        line="#ff00ff",
        accent="#00ffff",
        accent_2="#ff00ff",
        accent_3="#ffff00",
        accent_4="#ff0055",
        hero_font='"Courier New", monospace',
        body_font='"Courier New", monospace',
        eyebrow="Cyberpunk Neon",
        hero_title="Neon glowing activity log.",
        hero_copy="Dark terminal aesthetic with neon pinks and cyans.",
        extra_css=".template-cyberpunk .panel, .template-cyberpunk .hero { box-shadow: 0 0 10px rgba(0, 255, 255, 0.2); border: 1px solid #00ffff; } .template-cyberpunk .chip { background: #1a1a1a; border: 1px solid #ff00ff; color: #ff00ff; } .template-cyberpunk h1, .template-cyberpunk h2 { text-shadow: 0 0 5px #00ffff; }",
    ),
    "glassmorphism": _theme(
        background_css="linear-gradient(135deg, #ff88cc 0%, #88ccff 100%)",
        overlay_css="radial-gradient(circle at 20% 30%, rgba(255,255,255,0.4), transparent 50%), radial-gradient(circle at 80% 70%, rgba(255,255,255,0.4), transparent 50%)",
        overlay_opacity="1",
        panel="rgba(255, 255, 255, 0.15)",
        panel_strong="rgba(255, 255, 255, 0.25)",
        ink="#1a1a1a",
        muted="#333333",
        line="rgba(255, 255, 255, 0.4)",
        accent="#ff33aa",
        accent_2="#33aaff",
        accent_3="#aa33ff",
        accent_4="#33ffaa",
        hero_font='"IBM Plex Sans", sans-serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Frosted Glass",
        hero_title="A blurred, soft, colorful look.",
        hero_copy="Vibrant background gradients peering through semi-transparent glass cards.",
        extra_css=".template-glassmorphism .panel, .template-glassmorphism .hero, .template-glassmorphism .chart-card, .template-glassmorphism .fact, .template-glassmorphism .repo-card { backdrop-filter: blur(16px); -webkit-backdrop-filter: blur(16px); border: 1px solid rgba(255,255,255,0.5); box-shadow: 0 8px 32px rgba(31, 38, 135, 0.15); border-radius: 20px; }",
    ),
    "brutalism": _theme(
        background_css="#ffffff",
        overlay_css="none",
        overlay_opacity="0",
        panel="#ffffff",
        panel_strong="#f0f0f0",
        ink="#000000",
        muted="#000000",
        line="#000000",
        accent="#ff3366",
        accent_2="#33ff99",
        accent_3="#3366ff",
        accent_4="#ffcc00",
        hero_font='"Helvetica Neue", Helvetica, Arial, sans-serif',
        body_font='"Helvetica Neue", Helvetica, Arial, sans-serif',
        eyebrow="Neo-Brutalism",
        hero_title="Stark borders. High contrast.",
        hero_copy="Loud and flat colors, oversized typography, thick solid lines, and aggressive drop shadows.",
        extra_css=".template-brutalism .panel, .template-brutalism .hero, .template-brutalism .fact, .template-brutalism .repo-card, .template-brutalism .chart-card { border: 4px solid #000; border-radius: 0; box-shadow: 8px 8px 0px #000; margin-bottom: 8px; background: #fff; } .template-brutalism .chip { border: 2px solid #000; border-radius: 0; font-weight: bold; background: #ffcc00; color: #000; } .template-brutalism * { color: #000 !important; } .template-brutalism .eyebrow { background: #ff3366; color: #000 !important; border: 4px solid #000; border-radius: 0; font-weight: bold; box-shadow: 4px 4px 0 #000; }",
    ),
    "retro_os": _theme(
        background_css="#008080",
        overlay_css="none",
        overlay_opacity="0",
        panel="#c0c0c0",
        panel_strong="#dfdfdf",
        ink="#000000",
        muted="#333333",
        line="#808080",
        accent="#000080",
        accent_2="#ff0000",
        accent_3="#008000",
        accent_4="#808000",
        hero_font='"MS Sans Serif", "Tahoma", sans-serif',
        body_font='"MS Sans Serif", "Tahoma", sans-serif',
        eyebrow="Classic OS Window",
        hero_title="Retro 95 interface look.",
        hero_copy="Window panels, beveled edges, gray backgrounds, and classic blue title bars.",
        extra_css=".template-retro_os .panel, .template-retro_os .hero, .template-retro_os .chart-card, .template-retro_os .fact, .template-retro_os .repo-card { border-top: 2px solid #fff; border-left: 2px solid #fff; border-right: 2px solid #000; border-bottom: 2px solid #000; border-radius: 0; background: #c0c0c0; } .template-retro_os .section-head { background: #000080; color: #fff; padding: 4px 8px; margin: -18px -18px 18px -18px; } .template-retro_os .section-head * { color: #fff !important; } .template-retro_os .chip { border: inset 2px; border-radius: 0; background: #dfdfdf; } .template-retro_os h1, .template-retro_os h2 { font-size: 1.5rem; letter-spacing: 0; }",
    ),
    "holo": _theme(
        background_css="linear-gradient(120deg, #e0c3fc 0%, #8ec5fc 100%)",
        overlay_css="linear-gradient(45deg, rgba(255,255,255,0.4) 0%, rgba(255,255,255,0) 50%, rgba(255,255,255,0.4) 100%)",
        overlay_opacity="1",
        panel="rgba(255, 255, 255, 0.4)",
        panel_strong="rgba(255, 255, 255, 0.6)",
        ink="#4a4a4a",
        muted="#6a6a6a",
        line="rgba(255, 255, 255, 0.6)",
        accent="#9933ff",
        accent_2="#00ccff",
        accent_3="#ff33cc",
        accent_4="#ffcc00",
        hero_font='"IBM Plex Sans", sans-serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Holographic Foil",
        hero_title="Iridescent and flowing.",
        hero_copy="Holographic gradient overlays, soft rounded borders, and light pastel highlights.",
        extra_css=".template-holo .panel, .template-holo .hero { border-radius: 30px; box-shadow: 0 10px 30px rgba(153, 51, 255, 0.15); backdrop-filter: blur(8px); } .template-holo .chip { background: linear-gradient(120deg, #fff 0%, rgba(255,255,255,0.5) 100%); border-radius: 20px; border: 1px solid rgba(255,255,255,0.8); }",
    ),
    "synthwave": _theme(
        background_css="linear-gradient(180deg, #2b003b 0%, #000000 100%)",
        overlay_css="linear-gradient(0deg, transparent 24%, rgba(255, 0, 127, 0.3) 25%, rgba(255, 0, 127, 0.3) 26%, transparent 27%, transparent 74%, rgba(0, 240, 255, 0.3) 75%, rgba(0, 240, 255, 0.3) 76%, transparent 77%, transparent), linear-gradient(90deg, transparent 24%, rgba(255, 0, 127, 0.3) 25%, rgba(255, 0, 127, 0.3) 26%, transparent 27%, transparent 74%, rgba(0, 240, 255, 0.3) 75%, rgba(0, 240, 255, 0.3) 76%, transparent 77%, transparent)",
        overlay_opacity="0.5",
        panel="rgba(20, 0, 40, 0.85)",
        panel_strong="rgba(30, 0, 60, 0.95)",
        ink="#ff00ff",
        muted="#00ffff",
        line="#ff007f",
        accent="#00f0ff",
        accent_2="#ff007f",
        accent_3="#ffff00",
        accent_4="#ff9900",
        hero_font='"Trebuchet MS", sans-serif',
        body_font='"Trebuchet MS", sans-serif',
        eyebrow="Synthwave Horizon",
        hero_title="Outrun the metrics.",
        hero_copy="Sunset gradients, wireframe horizons, and loud 80s aesthetic.",
        extra_css=".template-synthwave .panel, .template-synthwave .hero { border: 2px solid #00f0ff; box-shadow: 0 0 15px #ff007f inset, 0 0 20px #ff007f; } .template-synthwave h1, .template-synthwave h2 { color: #ff007f; text-shadow: 2px 2px 0 #00f0ff; text-transform: uppercase; font-style: italic; }",
    ),
    "paper": _theme(
        background_css="#e6dec3",
        overlay_css="radial-gradient(circle at center, rgba(0,0,0,0) 0%, rgba(0,0,0,0.1) 100%)",
        overlay_opacity="1",
        panel="#efe8d1",
        panel_strong="#f5eedc",
        ink="#2a2622",
        muted="#5a5247",
        line="rgba(0,0,0,0.1)",
        accent="#8c2e2e",
        accent_2="#234020",
        accent_3="#2a3a52",
        accent_4="#6e4f20",
        hero_font='"Palatino Linotype", "Book Antiqua", Palatino, serif',
        body_font='"Palatino Linotype", "Book Antiqua", Palatino, serif',
        eyebrow="Ink on Paper",
        hero_title="Typewriter bleed on textured paper.",
        hero_copy="Warm sepia tones, bookish typography, and a distinct analog print feel.",
        extra_css=".template-paper .panel, .template-paper .hero, .template-paper .chart-card, .template-paper .fact, .template-paper .repo-card { border: none; box-shadow: 2px 4px 10px rgba(0,0,0,0.08); position: relative; } .template-paper .panel::before, .template-paper .hero::before { content: ''; position: absolute; inset: 0; border: 1px solid rgba(0,0,0,0.1); border-radius: 4px; pointer-events: none; mix-blend-mode: multiply; filter: url(#paper-texture); }",
    ),
    "monochrome": _theme(
        background_css="#ffffff",
        overlay_css="none",
        overlay_opacity="0",
        panel="#ffffff",
        panel_strong="#fafafa",
        ink="#000000",
        muted="#666666",
        line="#e0e0e0",
        accent="#000000",
        accent_2="#333333",
        accent_3="#111111",
        accent_4="#444444",
        hero_font='"Helvetica Neue", Arial, sans-serif',
        body_font='"Helvetica Neue", Arial, sans-serif',
        eyebrow="Strict Monochrome",
        hero_title="Information design reduced to black and white.",
        hero_copy="Complete removal of color. Pure typographic hierarchy and stark geometric lines.",
        extra_css=".template-monochrome * { filter: grayscale(100%); } .template-monochrome .panel, .template-monochrome .hero { border-radius: 0; border: 1px solid #000; box-shadow: none; } .template-monochrome .chip { border-radius: 0; border: 1px solid #000; background: transparent; color: #000; }",
    ),
    "matrix": _theme(
        background_css="#000000",
        overlay_css="none",
        overlay_opacity="0",
        panel="rgba(0, 20, 0, 0.8)",
        panel_strong="rgba(0, 30, 0, 0.9)",
        ink="#00ff41",
        muted="#008f11",
        line="#003b00",
        accent="#00ff41",
        accent_2="#008f11",
        accent_3="#00ff41",
        accent_4="#008f11",
        hero_font='"Courier New", Courier, monospace',
        body_font='"Courier New", Courier, monospace',
        eyebrow="Digital Rain",
        hero_title="Wake up, Neo.",
        hero_copy="Terminal green aesthetics over deep black, strictly monospaced data output.",
        extra_css=".template-matrix .panel, .template-matrix .hero, .template-matrix .chart-card, .template-matrix .fact, .template-matrix .repo-card { border: 1px solid #008f11; border-radius: 0; box-shadow: 0 0 8px rgba(0, 255, 65, 0.2); } .template-matrix h1, .template-matrix h2, .template-matrix .eyebrow { text-shadow: 0 0 5px #00ff41; } .template-matrix .chip { background: #001a00; color: #00ff41; border: 1px solid #00ff41; border-radius: 0; }",
    ),
    "liquid": _theme(
        background_css="linear-gradient(45deg, #ff9a9e 0%, #fecfef 99%, #fecfef 100%)",
        overlay_css="none",
        overlay_opacity="0",
        panel="rgba(255, 255, 255, 0.6)",
        panel_strong="rgba(255, 255, 255, 0.8)",
        ink="#4a4a4a",
        muted="#8a8a8a",
        line="rgba(255, 255, 255, 0.5)",
        accent="#ff4d88",
        accent_2="#4d88ff",
        accent_3="#88ff4d",
        accent_4="#ffcc00",
        hero_font='"Quicksand", sans-serif',
        body_font='"Quicksand", sans-serif',
        eyebrow="Liquid Morph",
        hero_title="Soft, organic, and fluid.",
        hero_copy="Morphing border radii, pastel gradients, and lack of sharp edges.",
        extra_css=".template-liquid .panel, .template-liquid .hero, .template-liquid .chart-card, .template-liquid .fact, .template-liquid .repo-card { border-radius: 40px 60px 50px 30px; box-shadow: 0 10px 20px rgba(0,0,0,0.05); } .template-liquid .chip { border-radius: 50%; padding: 10px 15px; } .template-liquid .profile-card img { border-radius: 40px 20px 50px 30px !important; }",
    ),
}


def get_theme(key: str) -> dict[str, Any]:
    return REPORT_THEMES.get(key, REPORT_THEMES["default"])
