from __future__ import annotations

from typing import Any


BASE_THEME = {
    "bg": "#f3ece3",
    "bg_alt": "#e6d8c8",
    "panel": "rgba(255, 251, 245, 0.86)",
    "panel_strong": "rgba(255, 248, 242, 0.96)",
    "ink": "#1d2430",
    "muted": "#5f6c7c",
    "line": "rgba(29, 36, 48, 0.11)",
    "accent": "#0f766e",
    "accent_2": "#d97706",
    "accent_3": "#1d4ed8",
    "accent_4": "#b91c1c",
    "shadow": "0 24px 60px rgba(17, 24, 39, 0.16)",
    "hero_font": '"IBM Plex Sans", "Trebuchet MS", sans-serif',
    "body_font": '"IBM Plex Sans", "Trebuchet MS", sans-serif',
    "mono_font": '"IBM Plex Mono", monospace',
    "radius_shell": "28px",
    "radius_card": "22px",
    "background_css": "linear-gradient(160deg, #f8f2e8 0%, #f1e6d6 52%, #eadbc9 100%)",
    "overlay_css": "radial-gradient(circle at top left, rgba(15, 118, 110, 0.12), transparent 28%), radial-gradient(circle at right, rgba(217, 119, 6, 0.08), transparent 24%)",
    "overlay_opacity": "1",
    "eyebrow": "GitHub activity report",
    "hero_title": "Your coding weather report, rendered with dramatic flair.",
    "hero_copy": "Commits, pull requests, issues, and language footprints are organized into a static report snapshot that can travel cleanly.",
    "profile_kicker": "Profile",
    "side_kicker": "Coverage",
    "side_title": "A readable snapshot of your coding season",
    "side_copy": "The report folds GitHub activity into a single page with charts, repo highlights, and some fun observations.",
    "stats_kicker": "Key stats",
    "stats_title": "Signal at a glance",
    "charts_kicker": "Timeline",
    "charts_kicker_2": "Code churn",
    "calendar_kicker": "Calendar",
    "language_kicker": "Languages",
    "heatmap_kicker": "Heatmap",
    "language_breakdown_kicker": "Breakdown",
    "language_breakdown_title": "Language mix",
    "highlights_kicker": "Highlights",
    "highlights_title": "Fun facts and notable spikes",
    "repo_kicker": "Repositories",
    "repo_title": "Where the work happened",
    "notes_kicker": "Notes",
    "notes_title": "Warnings and caveats",
    "extra_css": "",
}


def _theme(**overrides: Any) -> dict[str, Any]:
    theme = dict(BASE_THEME)
    theme.update(overrides)
    return theme


REPORT_THEMES: dict[str, dict[str, Any]] = {
    "default": _theme(),
    "ledger": _theme(
        background_css="linear-gradient(180deg, #fbf6ef 0%, #f2e8d8 60%, #eadbc2 100%)",
        overlay_css="linear-gradient(rgba(31, 41, 55, 0.045) 1px, transparent 1px), linear-gradient(90deg, rgba(31, 41, 55, 0.03) 1px, transparent 1px)",
        overlay_opacity="0.7",
        panel="rgba(255, 252, 247, 0.9)",
        panel_strong="rgba(255, 253, 250, 0.98)",
        ink="#241d1a",
        muted="#6b625c",
        line="rgba(36, 29, 26, 0.12)",
        accent="#7b2d26",
        accent_2="#b08968",
        accent_3="#3b4d61",
        accent_4="#8f5f2d",
        hero_font='Georgia, "Times New Roman", serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="The Maintainer's Ledger",
        hero_title="A quarter-end statement for your GitHub output.",
        hero_copy="Less dashboard, more polished ledger: totals, cadence, and repo performance laid out like an annual report.",
        stats_title="Performance statement",
        repo_title="Portfolio holdings",
        highlights_title="Notable movements",
        extra_css=".template-ledger .panel,.template-ledger .hero{border-radius:14px}.template-ledger .chip,.template-ledger .eyebrow{border-radius:4px}.template-ledger h1,.template-ledger h2,.template-ledger h3{letter-spacing:-0.02em}",
    ),
    "transit": _theme(
        background_css="linear-gradient(180deg, #fcfbf6 0%, #f4f0e6 100%)",
        overlay_css="linear-gradient(rgba(52, 52, 52, 0.08) 2px, transparent 2px), linear-gradient(90deg, rgba(52, 52, 52, 0.08) 2px, transparent 2px)",
        overlay_opacity="0.22",
        panel="rgba(255,255,255,0.88)",
        panel_strong="rgba(255,255,255,0.96)",
        ink="#23262b",
        muted="#68707b",
        line="rgba(35,38,43,0.1)",
        accent="#006da8",
        accent_2="#ed8b00",
        accent_3="#00a56a",
        accent_4="#d64545",
        hero_font='"Arial Narrow", "IBM Plex Sans", sans-serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Merge Line Transit Map",
        hero_title="Follow the lines your work took through the network.",
        hero_copy="This version treats your activity like a transit system: routes, stations, and transfers between repos and rhythms.",
        repo_title="Transit lines",
        highlights_title="Stations worth stopping at",
        extra_css=".template-transit .hero,.template-transit .panel{border-radius:18px}.template-transit .chip,.template-transit .eyebrow{font-weight:700}.template-transit .accent-1,.template-transit .accent-2,.template-transit .accent-3,.template-transit .accent-4{border-top-width:6px}",
    ),
    "archive": _theme(
        background_css="linear-gradient(180deg, #f4efe8 0%, #e9dfd3 100%)",
        overlay_css="radial-gradient(circle at top left, rgba(87, 74, 60, 0.08), transparent 25%), radial-gradient(circle at bottom right, rgba(42, 65, 74, 0.08), transparent 22%)",
        panel="rgba(249, 243, 236, 0.88)",
        panel_strong="rgba(252, 248, 243, 0.98)",
        ink="#312822",
        muted="#786d66",
        line="rgba(49,40,34,0.12)",
        accent="#7f5539",
        accent_2="#5c7c72",
        accent_3="#b08968",
        accent_4="#5a6778",
        hero_font='"Palatino Linotype", Georgia, serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Archive Exhibit",
        hero_title="A curated exhibit of your recent GitHub artifacts.",
        hero_copy="Repos become exhibit pieces, charts become labels, and the whole thing reads like a small museum wall for your coding period.",
        side_title="Artifact framing for technical work",
        repo_title="Featured artifacts",
        highlights_title="Curator notes",
        extra_css=".template-archive .hero,.template-archive .panel{box-shadow:0 18px 40px rgba(74,54,40,0.14)}.template-archive .chip,.template-archive .eyebrow{background:rgba(255,255,255,0.55)}",
    ),
    "scrapbook": _theme(
        background_css="linear-gradient(180deg, #fff7ea 0%, #ffe9dd 100%)",
        overlay_css="radial-gradient(circle at top left, rgba(255, 140, 102, 0.16), transparent 24%), radial-gradient(circle at right, rgba(31, 176, 255, 0.14), transparent 22%)",
        panel="rgba(255, 250, 245, 0.86)",
        panel_strong="rgba(255, 252, 248, 0.98)",
        ink="#2b1c18",
        muted="#7a655f",
        line="rgba(43,28,24,0.1)",
        accent="#ff6b57",
        accent_2="#ffbd2f",
        accent_3="#1fb0ff",
        accent_4="#37b56e",
        hero_font='"Trebuchet MS", "Arial Narrow", sans-serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Indie Dev Scrapbook",
        hero_title="A loud little collage of what you shipped and nudged forward.",
        hero_copy="Messier on purpose, brighter on purpose, and much more like a launch diary than a KPI console.",
        highlights_title="Pinned moments",
        repo_title="Stickered repositories",
        extra_css=".template-scrapbook .hero,.template-scrapbook .panel{transform:rotate(-0.2deg)}.template-scrapbook .repo-card:nth-child(even),.template-scrapbook .fact:nth-child(odd){transform:rotate(0.5deg)}.template-scrapbook .chip,.template-scrapbook .eyebrow{box-shadow:3px 3px 0 rgba(0,0,0,0.08)}",
    ),
    "orbital": _theme(
        background_css="radial-gradient(circle at top left, rgba(32, 148, 255, 0.16), transparent 26%), linear-gradient(180deg, #050913 0%, #0a1020 56%, #0d1630 100%)",
        overlay_css="linear-gradient(rgba(90, 216, 255, 0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(90, 216, 255, 0.08) 1px, transparent 1px)",
        overlay_opacity="0.35",
        panel="rgba(6, 11, 22, 0.84)",
        panel_strong="rgba(8, 14, 28, 0.96)",
        ink="#e7f2ff",
        muted="#95a8c5",
        line="rgba(90,216,255,0.14)",
        accent="#5ad8ff",
        accent_2="#9ff5a4",
        accent_3="#f2b15d",
        accent_4="#ff8573",
        hero_font='"IBM Plex Sans", sans-serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Orbital Telemetry Brief",
        hero_title="Mission telemetry for a very online coding vessel.",
        hero_copy="An operational debrief version of your GitHub activity, tuned like a mission packet rather than a product dashboard.",
        side_title="Flight path summary",
        repo_title="Systems touched",
        highlights_title="Telemetry anomalies",
        extra_css=".template-orbital .panel,.template-orbital .hero{backdrop-filter:blur(24px)}.template-orbital .chip,.template-orbital .eyebrow{text-shadow:0 0 16px rgba(90,216,255,0.18)}",
    ),
    "fieldnotes": _theme(
        background_css="linear-gradient(180deg, #f7f1e5 0%, #efe4cf 100%)",
        overlay_css="linear-gradient(rgba(93, 83, 67, 0.05) 1px, transparent 1px)",
        overlay_opacity="0.6",
        panel="rgba(252, 247, 239, 0.88)",
        panel_strong="rgba(255, 251, 245, 0.98)",
        ink="#2f2821",
        muted="#706760",
        line="rgba(47,40,33,0.1)",
        accent="#466a62",
        accent_2="#b25c42",
        accent_3="#7d8c4c",
        accent_4="#9b7c3e",
        hero_font='"Georgia", serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Field Notes",
        hero_title="An expedition log through your recent coding terrain.",
        hero_copy="Notebook logic, margin-note energy, and a little bit of naturalist observation layered on top of the raw GitHub facts.",
        side_title="Collected observations",
        highlights_title="Notebook callouts",
        repo_title="Observed repositories",
        extra_css=".template-fieldnotes .hero,.template-fieldnotes .panel{border-radius:10px}.template-fieldnotes .language-item,.template-fieldnotes .warning,.template-fieldnotes .fact{background:rgba(255,255,255,0.55)}",
    ),
    "signalroom": _theme(
        background_css="linear-gradient(180deg, #060c10 0%, #0b1218 100%)",
        overlay_css="repeating-linear-gradient(180deg, rgba(159,245,164,0.06) 0 2px, transparent 2px 5px)",
        overlay_opacity="0.24",
        panel="rgba(8, 13, 18, 0.84)",
        panel_strong="rgba(10, 16, 22, 0.96)",
        ink="#dcffeb",
        muted="#8ab29b",
        line="rgba(159,245,164,0.14)",
        accent="#9ff5a4",
        accent_2="#f2b15d",
        accent_3="#5ad8ff",
        accent_4="#ff8573",
        hero_font='"Arial Narrow", "IBM Plex Sans", sans-serif',
        body_font='"IBM Plex Sans", sans-serif',
        mono_font='"IBM Plex Mono", monospace',
        eyebrow="Signal Room",
        hero_title="Your development channels, routed through the signal board.",
        hero_copy="A darker broadcast-room interpretation of the same GitHub snapshot: channels, feeds, and pulsing telemetry cues.",
        side_title="Channel summary",
        highlights_title="Signal spikes",
        repo_title="Active feeds",
        extra_css=".template-signalroom .chart-card canvas{filter:saturate(0.85) brightness(0.92)}.template-signalroom .chip,.template-signalroom .eyebrow{background:rgba(159,245,164,0.06)}",
    ),
    "gallery": _theme(
        background_css="linear-gradient(180deg, #f5f0ea 0%, #e9dfd4 100%)",
        overlay_css="radial-gradient(circle at top left, rgba(32, 80, 132, 0.12), transparent 24%), radial-gradient(circle at bottom right, rgba(181, 127, 60, 0.12), transparent 20%)",
        panel="rgba(250, 247, 242, 0.88)",
        panel_strong="rgba(255, 252, 247, 0.98)",
        ink="#2c2632",
        muted="#746d7a",
        line="rgba(44,38,50,0.1)",
        accent="#315ca8",
        accent_2="#b57f3c",
        accent_3="#7f3c8d",
        accent_4="#cc5f2f",
        hero_font='"Georgia", serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Gallery Wall",
        hero_title="A salon-style hanging of your GitHub tendencies.",
        hero_copy="Designed like a poster exhibition: asymmetry, oversized labels, and a more art-directed rhythm for the same analytics.",
        side_title="Curated frame notes",
        highlights_title="Wall text",
        repo_title="Framed projects",
        extra_css=".template-gallery .facts-grid,.template-gallery .repo-grid{grid-template-columns:1.2fr .8fr}.template-gallery .fact:nth-child(3n){transform:translateY(14px)}",
    ),
    "tapearchive": _theme(
        background_css="linear-gradient(180deg, #f6f2ea 0%, #ece4d7 100%)",
        overlay_css="linear-gradient(90deg, rgba(0,0,0,0.04) 0 6%, transparent 6% 100%)",
        overlay_opacity="0.22",
        panel="rgba(252, 249, 244, 0.88)",
        panel_strong="rgba(255, 252, 248, 0.98)",
        ink="#221f22",
        muted="#6d676e",
        line="rgba(34,31,34,0.1)",
        accent="#111111",
        accent_2="#ffb100",
        accent_3="#00a6a6",
        accent_4="#ff6b57",
        hero_font='"Arial Narrow", "IBM Plex Sans", sans-serif',
        body_font='"IBM Plex Sans", sans-serif',
        eyebrow="Tape Archive",
        hero_title="Boxed, labeled, and filed: your work in archival strips.",
        hero_copy="A tactile index-card and cassette-case take on coding activity, leaning modular and nostalgic without becoming retro terminal cosplay.",
        side_title="Archive metadata",
        highlights_title="Labeled moments",
        repo_title="Catalog entries",
        extra_css=".template-tapearchive .chip,.template-tapearchive .eyebrow{border-radius:4px}.template-tapearchive .repo-card,.template-tapearchive .fact{box-shadow:4px 4px 0 rgba(0,0,0,0.06)}",
    ),
}


def get_theme(key: str) -> dict[str, Any]:
    return REPORT_THEMES.get(key, REPORT_THEMES["default"])
